### ISSUE TITLE
Edge Understanding of Graphormer

### ISSUE THREAD

**Issue by egeozsoy** [microsoft/Graphormer#31]
It looks like the only use of edge encodings right now is to change the bias of the attention, so in a toy example where there are just two identical nodes with a single edge between them, with the edge label(edge feature) either 0 or 1, and a binary classification task, where the wanted prediction is the label of this edge, how would the network solve this task? Just using the edge encoding as attention bias should not be enough here right? I am asking because, I successfully applied graphormer to a similer task, but now I am not exactly sure how it works

**Comment by zhengsx** [comment]
Hi @egeozsoy , glad to see that Graphormer works on your task. Indeed, for the case about two identical nodes, edge encoding could not help it to distingush each other due to the weighted-sum (in self-attention) would fail when the representations of node are same. The possible reason of why Graphormer is successfully applied to the similar task, might be that the two nodes are not exactly same or there is a third node in your actual system.

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
