### ISSUE TITLE
question about code 

### ISSUE THREAD

**Issue by tanghui2017108** [microsoft/Graphormer#34]
Hello:
I have a little question when runing your code.

![image](https://user-images.githubusercontent.com/32611793/142258854-461e7707-23ec-45fb-acce-38f0f77130f4.png)
 
Why execute the else statement and not execute if statement .

**Comment by zhengsx** [comment]
Hi, it depends on what type of `idx `passed in, and the esle statement is for slice indices. Would you please provide more information about how you instantiate `MyGraphPropPredDataset `and call the `__getitem__`?

**Comment by tanghui2017108** [comment]
Thank your reply quickly.

I run the pcab.sh and  hiv.sh scripts, I did not modify the codes. But cannot running, so I debug the codes and found not execute if statement. 
![image](https://user-images.githubusercontent.com/32611793/142339389-0492e741-d9d4-4314-8dae-05fb5c76aac2.png)

**Comment by zhengsx** [comment]
It seems that the error occurs when loading OGB dataset. We warp the dataloader in original OGB library, therefore I wonder
1. do you check your python package environment with the requirements?
2. Could you run OGB's official test case, e.g., [here](https://github.com/snap-stanford/ogb/tree/master/examples/graphproppred/mol).
3. The error message seems to be covered by the multiprocessing package, would you try to set `num_workers=1` to see the error message?
By the way, please note that the pre_trained model should be well prepared at [here](https://github.com/microsoft/Graphormer/blob/main/examples/ogb/hiv.sh#L17) if you want to run hiv or pcba ([here](https://github.com/microsoft/Graphormer/blob/main/examples/ogb/pcba.sh#L17)). And we recommend to run the code under Linux, since we have not tested the code under Windows.

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
